# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\karakurt\Documents\GitHub\Project\insertpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 600)
        MainWindow.setStyleSheet("background-color: rgb(54, 100, 139);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.B_exit = QtWidgets.QPushButton(self.centralwidget)
        self.B_exit.setGeometry(QtCore.QRect(660, 370, 101, 41))
        self.B_exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.B_exit.setCheckable(False)
        self.B_exit.setObjectName("B_exit")
        self.eightB = QtWidgets.QPushButton(self.centralwidget)
        self.eightB.setGeometry(QtCore.QRect(380, 440, 50, 50))
        self.eightB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.eightB.setObjectName("eightB")
        self.threeB = QtWidgets.QPushButton(self.centralwidget)
        self.threeB.setGeometry(QtCore.QRect(470, 320, 50, 50))
        self.threeB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.threeB.setObjectName("threeB")
        self.zeroB = QtWidgets.QPushButton(self.centralwidget)
        self.zeroB.setGeometry(QtCore.QRect(380, 500, 50, 50))
        self.zeroB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.zeroB.setObjectName("zeroB")
        self.oneB = QtWidgets.QPushButton(self.centralwidget)
        self.oneB.setGeometry(QtCore.QRect(289, 319, 51, 51))
        self.oneB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.oneB.setObjectName("oneB")
        self.delB = QtWidgets.QPushButton(self.centralwidget)
        self.delB.setGeometry(QtCore.QRect(470, 500, 50, 50))
        self.delB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.delB.setObjectName("delB")
        self.nineB = QtWidgets.QPushButton(self.centralwidget)
        self.nineB.setGeometry(QtCore.QRect(470, 440, 50, 50))
        self.nineB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.nineB.setObjectName("nineB")
        self.fiveB = QtWidgets.QPushButton(self.centralwidget)
        self.fiveB.setGeometry(QtCore.QRect(380, 380, 50, 50))
        self.fiveB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.fiveB.setObjectName("fiveB")
        self.sevenB = QtWidgets.QPushButton(self.centralwidget)
        self.sevenB.setGeometry(QtCore.QRect(290, 440, 50, 50))
        self.sevenB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.sevenB.setObjectName("sevenB")
        self.la_name = QtWidgets.QLabel(self.centralwidget)
        self.la_name.setGeometry(QtCore.QRect(290, 160, 231, 41))
        self.la_name.setStyleSheet("color: rgb(54, 100, 139);\n"
"font: 63 8pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);")
        self.la_name.setAlignment(QtCore.Qt.AlignCenter)
        self.la_name.setObjectName("la_name")
        self.sixB = QtWidgets.QPushButton(self.centralwidget)
        self.sixB.setGeometry(QtCore.QRect(470, 380, 50, 50))
        self.sixB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.sixB.setObjectName("sixB")
        self.twoB = QtWidgets.QPushButton(self.centralwidget)
        self.twoB.setGeometry(QtCore.QRect(380, 320, 50, 50))
        self.twoB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.twoB.setObjectName("twoB")
        self.la_balance = QtWidgets.QLabel(self.centralwidget)
        self.la_balance.setGeometry(QtCore.QRect(290, 40, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.la_balance.setFont(font)
        self.la_balance.setStyleSheet("color: rgb(54, 100, 139);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);")
        self.la_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.la_balance.setObjectName("la_balance")
        self.li_amount_withdraw = QtWidgets.QLineEdit(self.centralwidget)
        self.li_amount_withdraw.setGeometry(QtCore.QRect(290, 210, 231, 41))
        self.li_amount_withdraw.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.li_amount_withdraw.setAlignment(QtCore.Qt.AlignCenter)
        self.li_amount_withdraw.setObjectName("li_amount_withdraw")
        self.li_balance = QtWidgets.QLineEdit(self.centralwidget)
        self.li_balance.setGeometry(QtCore.QRect(290, 90, 231, 41))
        self.li_balance.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.li_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.li_balance.setObjectName("li_balance")
        self.fourB = QtWidgets.QPushButton(self.centralwidget)
        self.fourB.setGeometry(QtCore.QRect(290, 380, 50, 50))
        self.fourB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.fourB.setObjectName("fourB")
        self.B_ok = QtWidgets.QPushButton(self.centralwidget)
        self.B_ok.setGeometry(QtCore.QRect(660, 490, 101, 41))
        self.B_ok.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"background-color: rgb(50, 173, 58);\n"
"\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20;\n"
"color: rgb(255, 255, 255);")
        self.B_ok.setCheckable(False)
        self.B_ok.setObjectName("B_ok")
        self.B_back = QtWidgets.QPushButton(self.centralwidget)
        self.B_back.setGeometry(QtCore.QRect(660, 430, 101, 41))
        self.B_back.setStyleSheet("background-color: rgb(240, 240, 119);\n"
"color: rgb(54, 100, 139);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20;\n"
"")
        self.B_back.setCheckable(False)
        self.B_back.setObjectName("B_back")
        self.clearB = QtWidgets.QPushButton(self.centralwidget)
        self.clearB.setGeometry(QtCore.QRect(290, 500, 50, 50))
        self.clearB.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt ;Montserrat SemiBold;\n"
"border-radius: 20 ;")
        self.clearB.setObjectName("clearB")
        self.la_error = QtWidgets.QLabel(self.centralwidget)
        self.la_error.setGeometry(QtCore.QRect(290, 270, 231, 31))
        self.la_error.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.la_error.setText("")
        self.la_error.setObjectName("la_error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.B_exit.setText(_translate("MainWindow", "Exit"))
        self.eightB.setText(_translate("MainWindow", "8"))
        self.threeB.setText(_translate("MainWindow", "3"))
        self.zeroB.setText(_translate("MainWindow", "0"))
        self.oneB.setText(_translate("MainWindow", "1"))
        self.delB.setText(_translate("MainWindow", "Del"))
        self.nineB.setText(_translate("MainWindow", "9"))
        self.fiveB.setText(_translate("MainWindow", "5"))
        self.sevenB.setText(_translate("MainWindow", "7"))
        self.la_name.setText(_translate("MainWindow", "Please enter amount of money to deposit:"))
        self.sixB.setText(_translate("MainWindow", "6"))
        self.twoB.setText(_translate("MainWindow", "2"))
        self.la_balance.setText(_translate("MainWindow", "CURRENT BALANCE"))
        self.fourB.setText(_translate("MainWindow", "4"))
        self.B_ok.setText(_translate("MainWindow", "Ok"))
        self.B_back.setText(_translate("MainWindow", "Back"))
        self.clearB.setText(_translate("MainWindow", "Clear"))
