# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\karakurt\Documents\GitHub\Project\newadminpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(54, 100, 139);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_baslik = QtWidgets.QLabel(self.centralwidget)
        self.label_baslik.setGeometry(QtCore.QRect(100, 0, 611, 81))
        self.label_baslik.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 18pt \"Montserrat SemiBold\";")
        self.label_baslik.setAlignment(QtCore.Qt.AlignCenter)
        self.label_baslik.setObjectName("label_baslik")
        self.B_updatecust = QtWidgets.QPushButton(self.centralwidget)
        self.B_updatecust.setGeometry(QtCore.QRect(270, 470, 251, 51))
        self.B_updatecust.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.B_updatecust.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20 ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\Project\\withdraw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_updatecust.setIcon(icon)
        self.B_updatecust.setIconSize(QtCore.QSize(40, 40))
        self.B_updatecust.setCheckable(False)
        self.B_updatecust.setObjectName("B_updatecust")
        self.B_newcust = QtWidgets.QPushButton(self.centralwidget)
        self.B_newcust.setGeometry(QtCore.QRect(270, 400, 251, 51))
        self.B_newcust.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.B_newcust.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20 ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\Project\\password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_newcust.setIcon(icon1)
        self.B_newcust.setIconSize(QtCore.QSize(40, 40))
        self.B_newcust.setCheckable(False)
        self.B_newcust.setObjectName("B_newcust")
        self.B_exit = QtWidgets.QPushButton(self.centralwidget)
        self.B_exit.setGeometry(QtCore.QRect(670, 480, 101, 41))
        self.B_exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.B_exit.setCheckable(False)
        self.B_exit.setObjectName("B_exit")
        self.B_info = QtWidgets.QPushButton(self.centralwidget)
        self.B_info.setGeometry(QtCore.QRect(270, 330, 251, 51))
        self.B_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.B_info.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 64, 89);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"border-radius: 20 ")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\Project\\deposit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_info.setIcon(icon2)
        self.B_info.setIconSize(QtCore.QSize(37, 37))
        self.B_info.setCheckable(False)
        self.B_info.setObjectName("B_info")
        self.la_total = QtWidgets.QLabel(self.centralwidget)
        self.la_total.setGeometry(QtCore.QRect(280, 100, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.la_total.setFont(font)
        self.la_total.setStyleSheet("color: rgb(54, 100, 139);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);")
        self.la_total.setAlignment(QtCore.Qt.AlignCenter)
        self.la_total.setObjectName("la_total")
        self.la_withdraw = QtWidgets.QLabel(self.centralwidget)
        self.la_withdraw.setGeometry(QtCore.QRect(130, 210, 251, 41))
        self.la_withdraw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.la_withdraw.setStyleSheet("color: rgb(54, 100, 139);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);")
        self.la_withdraw.setAlignment(QtCore.Qt.AlignCenter)
        self.la_withdraw.setObjectName("la_withdraw")
        self.la_deposit = QtWidgets.QLabel(self.centralwidget)
        self.la_deposit.setGeometry(QtCore.QRect(400, 210, 241, 41))
        self.la_deposit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.la_deposit.setStyleSheet("color: rgb(54, 100, 139);\n"
"font: 63 14pt \"Montserrat SemiBold\";\n"
"background-color: rgb(255, 255, 255);")
        self.la_deposit.setAlignment(QtCore.Qt.AlignCenter)
        self.la_deposit.setObjectName("la_deposit")
        self.la_totalmoney = QtWidgets.QLabel(self.centralwidget)
        self.la_totalmoney.setGeometry(QtCore.QRect(280, 150, 231, 41))
        self.la_totalmoney.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.la_totalmoney.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.la_totalmoney.setFrameShape(QtWidgets.QFrame.Box)
        self.la_totalmoney.setText("")
        self.la_totalmoney.setAlignment(QtCore.Qt.AlignCenter)
        self.la_totalmoney.setObjectName("la_totalmoney")
        self.la_dailywithdraw = QtWidgets.QLabel(self.centralwidget)
        self.la_dailywithdraw.setGeometry(QtCore.QRect(130, 260, 251, 41))
        self.la_dailywithdraw.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.la_dailywithdraw.setFrameShape(QtWidgets.QFrame.Box)
        self.la_dailywithdraw.setText("")
        self.la_dailywithdraw.setAlignment(QtCore.Qt.AlignCenter)
        self.la_dailywithdraw.setObjectName("la_dailywithdraw")
        self.la_dailydeposit = QtWidgets.QLabel(self.centralwidget)
        self.la_dailydeposit.setGeometry(QtCore.QRect(400, 260, 241, 41))
        self.la_dailydeposit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Montserrat SemiBold\";")
        self.la_dailydeposit.setFrameShape(QtWidgets.QFrame.Box)
        self.la_dailydeposit.setText("")
        self.la_dailydeposit.setAlignment(QtCore.Qt.AlignCenter)
        self.la_dailydeposit.setObjectName("la_dailydeposit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_baslik.setText(_translate("MainWindow", "ADMIN SCREEN"))
        self.B_updatecust.setText(_translate("MainWindow", "Update Customer Info"))
        self.B_newcust.setText(_translate("MainWindow", "New Customer"))
        self.B_exit.setText(_translate("MainWindow", "EXIT"))
        self.B_info.setText(_translate("MainWindow", "Customer Info"))
        self.la_total.setText(_translate("MainWindow", "TOTAL MONEY"))
        self.la_withdraw.setText(_translate("MainWindow", "Daily Withdrawn Money"))
        self.la_deposit.setText(_translate("MainWindow", "Daily Deposited Money"))
